#!/usr/bin/env python3
"""Merge two asm2arm_tool JIT-mode _subr.go files that differ only in SVE
vector length into one carrying both sets of frame metadata.

asm2arm_tool's --vl feeds only CalcSPDelta: the emitted machine code is
identical for every vector length, because SVE encodings are vector-length
agnostic. What changes is the frame accounting handed to Go -- _stack__X and the
pcsp SP deltas -- because scalable spill slots are VL bytes wide.

Baking one vector length in means the natives are only correct on hardware of
that exact width; anywhere else Go computes the wrong caller SP and precise GC
stack scanning walks the wrong frame. Since the text is shared, the fix costs
almost nothing: keep one copy of the code and one small table per VL, and pick
at load time.

Usage: merge_vl_subr.py <vl_a> <subr_a.go> <vl_b> <subr_b.go> <out.go>
"""

import re
import sys


def parse(path):
    src = open(path, encoding="utf-8").read()
    out = {}
    for key in ("_entry", "_stack", "_size"):
        m = re.search(r"(%s__\w+)\s*=\s*(\d+)" % key, src)
        if not m:
            raise SystemExit("%s: no %s constant found" % (path, key))
        out[key] = (m.group(1), m.group(2))
    m = re.search(r"(_pcsp__\w+)\s*=\s*\[\]\[2\]uint32\{(.*?)\n\s*\}", src, re.S)
    if not m:
        raise SystemExit("%s: no pcsp table found" % path)
    out["_pcsp"] = (m.group(1), m.group(2).rstrip())
    m = re.search(r"package\s+(\w+)", src)
    out["package"] = m.group(1)
    m = re.search(r'\{"(\w+)_entry"', src)
    out["entry_sym"] = m.group(1)
    return out


def main():
    if len(sys.argv) != 6:
        raise SystemExit(__doc__)
    vl_a, path_a, vl_b, path_b, out_path = sys.argv[1:]
    a, b = parse(path_a), parse(path_b)

    if a["_size"][1] != b["_size"][1] or a["_entry"][1] != b["_entry"][1]:
        raise SystemExit(
            "refusing to merge: entry/size differ between vl=%s and vl=%s, so the\n"
            "text is not vector-length agnostic and a shared copy would be wrong"
            % (vl_a, vl_b)
        )

    name = a["_pcsp"][0][len("_pcsp__"):]
    sym = a["entry_sym"]
    variants = ((vl_a, a), (vl_b, b))

    L = []
    L.append("// +build !noasm !appengine")
    L.append("// Code generated by asm2asm_tool, DO NOT EDIT.")
    L.append("")
    L.append("package %s" % a["package"])
    L.append("")
    L.append('import (')
    L.append('\t"github.com/bytedance/sonic/loader"')
    L.append(')')
    L.append("")
    L.append("const (")
    L.append("\t_entry__%s = %s" % (name, a["_entry"][1]))
    L.append(")")
    L.append("")
    L.append("const (")
    for vl, v in variants:
        L.append("\t_stack__%s_vl%s = %s" % (name, vl, v["_stack"][1]))
    L.append(")")
    L.append("")
    L.append("const (")
    L.append("\t_size__%s = %s" % (name, a["_size"][1]))
    L.append(")")
    L.append("")
    L.append("var (")
    for vl, v in variants:
        L.append("\t_pcsp__%s_vl%s = [][2]uint32{" % (name, vl))
        for line in v["_pcsp"][1].splitlines():
            line = line.strip()
            if line:
                L.append("\t\t%s" % line)
        L.append("\t}")
    L.append(")")
    L.append("")
    L.append("// _cfunc_%s returns the frame metadata for an SVE vector length of vl" % name)
    L.append("// bytes, or nil if the natives were not generated for that width.")
    L.append("func _cfunc_%s(vl int) []loader.CFunc {" % name)
    L.append("\tswitch vl {")
    for vl, _ in variants:
        L.append("\tcase %s:" % vl)
        L.append("\t\treturn []loader.CFunc{")
        L.append('\t\t\t{"%s_entry", 0, _entry__%s, 0, nil},' % (sym, name))
        L.append(
            '\t\t\t{"%s", _entry__%s, _size__%s, _stack__%s_vl%s, _pcsp__%s_vl%s},'
            % (sym, name, name, name, vl, name, vl)
        )
        L.append("\t\t}")
    L.append("\t}")
    L.append("\treturn nil")
    L.append("}")
    L.append("")
    open(out_path, "w", encoding="utf-8").write("\n".join(L))


if __name__ == "__main__":
    main()
