//go:build !noasm || !appengine
// +build !noasm !appengine

// Code generated by asm2asm_tool, DO NOT EDIT.

package sve_wrapgoc

import (
	"github.com/bytedance/sonic/loader"
)

const (
	_entry__skip_one_fast = 0
)

const (
	_stack__skip_one_fast = 176
)

const (
	_size__skip_one_fast = 2916
)

var (
	_pcsp__skip_one_fast = [][2]uint32{
		{0x1, 0},
		{0x10, 128},
		{0x14, 160},
		{0x118, 176},
		{0x11c, 160},
		{0x128, 128},
		{0x12c, 0},
		{0x9a0, 176},
		{0x9a4, 160},
		{0x9b0, 128},
		{0x9b4, 0},
		{0x9c0, 176},
		{0x9c4, 160},
		{0x9d0, 128},
		{0x9d4, 0},
		{0x9f4, 176},
		{0x9f8, 160},
		{0xa04, 128},
		{0xa08, 0},
		{0xaa4, 176},
		{0xaa8, 160},
		{0xab4, 128},
		{0xab8, 0},
		{0xb64, 176},
	}
)

var _cfunc_skip_one_fast = []loader.CFunc{
	{"_skip_one_fast_entry", 0, _entry__skip_one_fast, 0, nil},
	{"_skip_one_fast", _entry__skip_one_fast, _size__skip_one_fast, _stack__skip_one_fast, _pcsp__skip_one_fast},
}
