//go:build !noasm || !appengine
// +build !noasm !appengine

// Code generated by asm2asm_tool, DO NOT EDIT.

package sve_wrapgoc

import (
	"github.com/bytedance/sonic/loader"
)

const (
	_entry__skip_one_fast = 0
)

const (
	_stack__skip_one_fast = 224
)

const (
	_size__skip_one_fast = 4324
)

var (
	_pcsp__skip_one_fast = [][2]uint32{
		{0x1, 0},
		{0x1c, 176},
		{0x20, 208},
		{0x101c, 224},
		{0x1020, 208},
		{0x1038, 176},
		{0x103c, 0},
		{0x10e4, 224},
	}
)

var _cfunc_skip_one_fast = []loader.CFunc{
	{"_skip_one_fast_entry", 0, _entry__skip_one_fast, 0, nil},
	{"_skip_one_fast", _entry__skip_one_fast, _size__skip_one_fast, _stack__skip_one_fast, _pcsp__skip_one_fast},
}
