//go:build !noasm || !appengine
// +build !noasm !appengine

// Code generated by asm2asm_tool, DO NOT EDIT.

package sve_wrapgoc

import (
	"github.com/bytedance/sonic/loader"
)

const (
	_entry__skip_one = 0
)

const (
	_stack__skip_one = 352
)

const (
	_size__skip_one = 19700
)

var (
	_pcsp__skip_one = [][2]uint32{
		{0x1, 0},
		{0x20, 272},
		{0x24, 336},
		{0x4888, 352},
		{0x488c, 336},
		{0x48a8, 272},
		{0x48ac, 0},
		{0x4cf4, 352},
	}
)

var _cfunc_skip_one = []loader.CFunc{
	{"_skip_one_entry", 0, _entry__skip_one, 0, nil},
	{"_skip_one", _entry__skip_one, _size__skip_one, _stack__skip_one, _pcsp__skip_one},
}
