// +build !noasm !appengine
// Code generated by asm2asm_tool, DO NOT EDIT.

package neon

import (
    `github.com/bytedance/sonic/loader`
)

const (
    _entry__get_by_path = 0
)

const (
    _stack__get_by_path = 240
)

const (
    _size__get_by_path = 21284
)

var (
    _pcsp__get_by_path = [][2]uint32{
        {0x1, 0},
        {0x4558, 240},
        {0x455c, 0},
        {0x5324, 240},
    }
)

var _cfunc_get_by_path = []loader.CFunc{
    {"_get_by_path_entry", 0, _entry__get_by_path, 0, nil},
    {"_get_by_path", _entry__get_by_path, _size__get_by_path, _stack__get_by_path, _pcsp__get_by_path},
}
