// +build !noasm !appengine
// Code generated by asm2asm_tool, DO NOT EDIT.

package neon

import (
    `github.com/bytedance/sonic/loader`
)

const (
    _entry__html_escape = 0
)

const (
    _stack__html_escape = 32
)

const (
    _size__html_escape = 5200
)

var (
    _pcsp__html_escape = [][2]uint32{
        {0x1, 0},
        {0x3d4, 32},
        {0x3d8, 0},
        {0x3e8, 32},
        {0x3ec, 0},
        {0x40c, 32},
        {0x410, 0},
        {0x428, 32},
        {0x42c, 0},
        {0x1450, 32},
    }
)

var _cfunc_html_escape = []loader.CFunc{
    {"_html_escape_entry", 0, _entry__html_escape, 0, nil},
    {"_html_escape", _entry__html_escape, _size__html_escape, _stack__html_escape, _pcsp__html_escape},
}
