/*
 * Copyright 2026 ByteDance Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package neon

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// The natives are compiled with `-ffixed-x28 -ffixed-x18 -ffixed-x9` (see
// tools/asm2arm_tool/scripts/generate_native_go.sh). Each of those registers is
// unusable by the generated code for a different reason:
//
//   - x28 is Go's goroutine (g) register on arm64. Clobbering it corrupts the
//     runtime's view of the current goroutine.
//   - x18 is the platform register. On Apple platforms (darwin/arm64) the kernel
//     does not preserve it across exception returns, so any value the natives
//     park there is asynchronously zeroed. This is not theoretical: a build that
//     lost -ffixed-x18 segfaulted on macOS with a fault address exactly equal to
//     the displacement of the first x18-relative load.
//   - x9 is reserved for asm2arm_tool's own codegen.
//
// These registers are reserved by compiler flags, so nothing in the normal build
// enforces them. Dropping a flag, or regenerating with a compiler that defaults
// to a triple where the register is allocatable, silently produces natives that
// pass every functional test on Linux and then crash elsewhere. This test pins
// the invariant to the checked-in artifacts instead.
//
// It reads the generated sources rather than the compiled package, so it is
// arch-independent and runs on every CI platform, not just arm64.
//
// Scoped to neon for now. internal/native/sve_linkname and
// internal/native/sve_wrapgoc were generated by the same flag-less pipeline and
// still carry x18, which is latent rather than live: those paths are selected
// only on SVE hardware, and the darwin/arm64 dispatch never reaches them
// because it probes /proc/cpuinfo, which does not exist there. Regenerating
// them needs an SVE host to test on, so it is handled separately; this guard
// should grow to cover them at that point.
var reservedRegs = []struct {
	name   string
	reason string
}{
	{"x28", "Go's goroutine (g) register on arm64"},
	{"x18", "the platform register; not preserved by the darwin/arm64 kernel"},
	{"x9", "reserved for asm2arm_tool's codegen"},
}

func TestGeneratedTextAvoidsReservedRegisters(t *testing.T) {
	files, err := filepath.Glob("*_text_arm64.go")
	if err != nil {
		t.Fatalf("glob generated text: %v", err)
	}
	if len(files) == 0 {
		t.Fatal("no *_text_arm64.go files found; the natives should be checked in alongside this test")
	}

	for _, reg := range reservedRegs {
		reg := reg
		t.Run(reg.name, func(t *testing.T) {
			// Match the 64- and 32-bit views of the same register, as whole
			// words so hex byte literals and immediates never match.
			re := regexp.MustCompile(`\b[wx]` + strings.TrimPrefix(reg.name, "x") + `\b`)
			for _, file := range files {
				for _, hit := range scanDisassembly(t, file, re) {
					t.Errorf("%s uses reserved register %s (%s): %s",
						file, reg.name, reg.reason, hit)
				}
			}
		})
	}
}

// scanDisassembly reports the disassembly comments in a generated *_text_arm64.go
// that match re. Only the text after "//" is considered, and the leading address
// is dropped, so the search sees instruction operands and nothing else.
func scanDisassembly(t *testing.T, file string, re *regexp.Regexp) []string {
	t.Helper()

	body, err := os.ReadFile(file)
	if err != nil {
		t.Fatalf("read %s: %v", file, err)
	}

	var hits []string
	for _, line := range strings.Split(string(body), "\n") {
		_, comment, ok := strings.Cut(line, "//")
		if !ok {
			continue
		}
		// Generated form is "// <hex address> \t<mnemonic>\t<operands>". Drop
		// the address so it can never be confused for an operand.
		asm := strings.TrimSpace(comment)
		if _, rest, ok := strings.Cut(asm, " "); ok {
			asm = rest
		}
		if re.MatchString(asm) {
			hits = append(hits, strings.Join(strings.Fields(asm), " "))
		}
	}
	return hits
}
