// +build !noasm !appengine
// Code generated by asm2asm_tool, DO NOT EDIT.

package neon

import (
    `github.com/bytedance/sonic/loader`
)

const (
    _entry__skip_array = 0
)

const (
    _stack__skip_array = 320
)

const (
    _size__skip_array = 15540
)

var (
    _pcsp__skip_array = [][2]uint32{
        {0x1, 0},
        {0x39f0, 320},
        {0x39f4, 0},
        {0x3cb4, 320},
    }
)

var _cfunc_skip_array = []loader.CFunc{
    {"_skip_array_entry", 0, _entry__skip_array, 0, nil},
    {"_skip_array", _entry__skip_array, _size__skip_array, _stack__skip_array, _pcsp__skip_array},
}
