// +build !noasm !appengine
// Code generated by asm2asm_tool, DO NOT EDIT.

package neon

import (
    `github.com/bytedance/sonic/loader`
)

const (
    _entry__skip_object = 0
)

const (
    _stack__skip_object = 320
)

const (
    _size__skip_object = 15540
)

var (
    _pcsp__skip_object = [][2]uint32{
        {0x1, 0},
        {0x39f0, 320},
        {0x39f4, 0},
        {0x3cb4, 320},
    }
)

var _cfunc_skip_object = []loader.CFunc{
    {"_skip_object_entry", 0, _entry__skip_object, 0, nil},
    {"_skip_object", _entry__skip_object, _size__skip_object, _stack__skip_object, _pcsp__skip_object},
}
