// +build !noasm !appengine
// Code generated by asm2asm_tool, DO NOT EDIT.

package neon

import (
    `github.com/bytedance/sonic/loader`
)

const (
    _entry__skip_one = 0
)

const (
    _stack__skip_one = 208
)

const (
    _size__skip_one = 14132
)

var (
    _pcsp__skip_one = [][2]uint32{
        {0x1, 0},
        {0x339c, 208},
        {0x33a0, 0},
        {0x3734, 208},
    }
)

var _cfunc_skip_one = []loader.CFunc{
    {"_skip_one_entry", 0, _entry__skip_one, 0, nil},
    {"_skip_one", _entry__skip_one, _size__skip_one, _stack__skip_one, _pcsp__skip_one},
}
