// +build !noasm !appengine
// Code generated by asm2asm_tool, DO NOT EDIT.

package neon

import (
    `github.com/bytedance/sonic/loader`
)

const (
    _entry__validate_utf8 = 0
)

const (
    _stack__validate_utf8 = 64
)

const (
    _size__validate_utf8 = 708
)

var (
    _pcsp__validate_utf8 = [][2]uint32{
        {0x1, 0},
        {0x27c, 64},
        {0x280, 0},
        {0x294, 64},
        {0x298, 0},
        {0x2ac, 64},
        {0x2b0, 0},
        {0x2c4, 64},
    }
)

var _cfunc_validate_utf8 = []loader.CFunc{
    {"_validate_utf8_entry", 0, _entry__validate_utf8, 0, nil},
    {"_validate_utf8", _entry__validate_utf8, _size__validate_utf8, _stack__validate_utf8, _pcsp__validate_utf8},
}
