// +build !noasm !appengine
// Code generated by asm2asm_tool, DO NOT EDIT.

package neon

import (
    `github.com/bytedance/sonic/loader`
)

const (
    _entry__vstring = 0
)

const (
    _stack__vstring = 144
)

const (
    _size__vstring = 2660
)

var (
    _pcsp__vstring = [][2]uint32{
        {0x1, 0},
        {0x9d0, 144},
        {0x9d4, 0},
        {0xa64, 144},
    }
)

var _cfunc_vstring = []loader.CFunc{
    {"_vstring_entry", 0, _entry__vstring, 0, nil},
    {"_vstring", _entry__vstring, _size__vstring, _stack__vstring, _pcsp__vstring},
}
